default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  port: <%= ENV['DATABASE_PORT'] || '5432' %>
  host: <%= ENV['DATABASE_HOST'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= "#{ENV['APP_NAME']}_development" %>

test:
  <<: *default
  database: <%= "#{ENV['APP_NAME']}_test" %>

production:
  <<: *default
  database: <%= "#{ENV['APP_NAME']}_production" %>