FROM ruby:<%=RUBY_VERSION%>

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev

RUN mkdir /<%=app_name%>

WORKDIR /<%=app_name%>

COPY Gemfile /<%=app_name%>/Gemfile

COPY Gemfile.lock /<%=app_name%>/Gemfile.lock

RUN bundle config build.nokogiri --use-system-libraries

RUN bundle check || bundle install

COPY . /<%=app_name%>

RUN useradd <%=app_name%>_user -m -u 1000

USER <%=app_name%>_user

ENTRYPOINT ["/<%=app_name%>/docker-entrypoint.sh"]