FROM ruby:<%=RUBY_VERSION%>

LABEL maintainer="<%=`git config user.name`%> <<%=`git config user.email`%>>"

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev

RUN mkdir /<%="#{app_name}_api"%>

WORKDIR /<%="#{app_name}_api"%>

COPY Gemfile /<%="#{app_name}_api"%>/Gemfile

COPY Gemfile.lock /<%="#{app_name}_api"%>/Gemfile.lock

RUN bundle config build.nokogiri --use-system-libraries

RUN bundle check || bundle install

COPY . /<%="#{app_name}_api"%>

ENTRYPOINT ["/<%="#{app_name}_api"%>/dockerscripts/api-entrypoint.sh"